import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import ICAL from "ical.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Load fixtures generated by Elm (via GenerateFixtures.elm).
 * This is the actual output of our Elm library — no hardcoded strings.
 */
const fixtures = JSON.parse(
  readFileSync(join(__dirname, "fixtures.json"), "utf-8")
);

function getFixture(name) {
  const fixture = fixtures.find((f) => f.name === name);
  assert.ok(fixture, `Fixture "${name}" not found`);
  return fixture.ics;
}

function parseCalendar(icsString) {
  const parsed = ICAL.parse(icsString);
  return new ICAL.Component(parsed);
}

function getEvent(calendar, index = 0) {
  const events = calendar.getAllSubcomponents("vevent");
  assert.ok(events.length > index, `Expected at least ${index + 1} event(s)`);
  return events[index];
}

describe("cross-reference: basic feed (from Elm output)", () => {
  let cal;

  before(() => {
    cal = parseCalendar(getFixture("basic-feed"));
  });

  it("parses without error", () => {
    assert.equal(cal.name, "vcalendar");
  });

  it("has correct calendar properties", () => {
    assert.equal(cal.getFirstPropertyValue("version"), "2.0");
    assert.equal(
      cal.getFirstPropertyValue("prodid"),
      "-//incrementalelm.com//elm-ical.tests//EN"
    );
  });

  it("has two events", () => {
    const events = cal.getAllSubcomponents("vevent");
    assert.equal(events.length, 2);
  });

  it("event 1 has correct properties", () => {
    const ev = getEvent(cal, 0);
    assert.equal(ev.getFirstPropertyValue("summary"), "repeating by month");
    assert.equal(ev.getFirstPropertyValue("description"), "repeating by month");
    assert.equal(ev.getFirstPropertyValue("uid"), "1@incrementalelm.com");
  });

  it("event 2 unescapes commas in text", () => {
    const ev = getEvent(cal, 1);
    assert.equal(
      ev.getFirstPropertyValue("summary"),
      "This is the title, it escapes commas"
    );
    assert.equal(
      ev.getFirstPropertyValue("description"),
      "This is the description, it escapes commas"
    );
  });
});

describe("cross-reference: event with created/last-modified (from Elm output)", () => {
  let cal;

  before(() => {
    cal = parseCalendar(getFixture("simple-event"));
  });

  it("parses without error", () => {
    assert.equal(cal.name, "vcalendar");
  });

  it("event has correct summary", () => {
    const ev = getEvent(cal);
    assert.equal(ev.getFirstPropertyValue("summary"), "Simple Event");
  });

  it("event has created and last-modified", () => {
    const ev = getEvent(cal);
    assert.ok(ev.getFirstPropertyValue("created"));
    assert.ok(ev.getFirstPropertyValue("last-modified"));
  });
});

describe("cross-reference: long description with line folding (from Elm output)", () => {
  let cal;

  before(() => {
    cal = parseCalendar(getFixture("long-description"));
  });

  it("parses without error", () => {
    assert.equal(cal.name, "vcalendar");
  });

  it("unfolds and unescapes description", () => {
    const ev = getEvent(cal);
    assert.equal(
      ev.getFirstPropertyValue("description"),
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.\nbeep boop"
    );
  });

  it("parses HTML description with FMTTYPE parameter", () => {
    const ev = getEvent(cal);
    const prop = ev.getFirstProperty("x-alt-desc");
    assert.ok(prop, "x-alt-desc property should exist");
    assert.equal(prop.getParameter("fmttype"), "text/html");
    assert.ok(prop.getFirstValue().includes("<p>"));
  });

  it("event has correct location", () => {
    const ev = getEvent(cal);
    assert.equal(ev.getFirstPropertyValue("location"), "localhost");
  });
});

describe("cross-reference: all-day event (from Elm output)", () => {
  let cal;

  before(() => {
    cal = parseCalendar(getFixture("all-day-event"));
  });

  it("parses without error", () => {
    assert.equal(cal.name, "vcalendar");
  });

  it("event has correct date start", () => {
    const ev = getEvent(cal);
    const dtstart = ev.getFirstProperty("dtstart");
    const val = dtstart.getFirstValue();
    assert.equal(val.isDate, true);
    assert.equal(val.year, 2021);
    assert.equal(val.month, 3);
    assert.equal(val.day, 18);
  });

  it("event has correct status and transparency", () => {
    const ev = getEvent(cal);
    assert.equal(ev.getFirstPropertyValue("status"), "CONFIRMED");
    assert.equal(ev.getFirstPropertyValue("transp"), "TRANSPARENT");
  });
});

describe("cross-reference: organizer (from Elm output)", () => {
  it("parses organizer with CN param", () => {
    const cal = parseCalendar(getFixture("organizer"));
    const ev = getEvent(cal);
    const org = ev.getFirstProperty("organizer");
    assert.ok(org, "organizer property should exist");
    assert.equal(org.getParameter("cn"), "Dillon Kearns");
    assert.equal(org.getFirstValue(), "mailto:dillon@incrementalelm.com");
  });
});

describe("cross-reference: double quotes in text (from Elm output)", () => {
  it("double quotes appear unescaped in parsed value", () => {
    const cal = parseCalendar(getFixture("double-quotes"));
    const ev = getEvent(cal);
    assert.equal(
      ev.getFirstPropertyValue("summary"),
      'She said "hello"'
    );
  });
});

describe("cross-reference: line folding respects byte length (from Elm output)", () => {
  it("no line exceeds 75 bytes", () => {
    const ics = getFixture("emoji");
    // Split on CRLF to get individual lines (unfolded lines start with space)
    const lines = ics.split("\r\n");
    for (const line of lines) {
      const byteLength = Buffer.byteLength(line, "utf-8");
      assert.ok(
        byteLength <= 75,
        `Line is ${byteLength} bytes (max 75): "${line}"`
      );
    }
  });

  it("emoji round-trips through parser correctly", () => {
    const cal = parseCalendar(getFixture("emoji"));
    const ev = getEvent(cal);
    const summary = ev.getFirstPropertyValue("summary");
    assert.ok(summary.includes("🎉"), "should contain party emoji");
    assert.ok(summary.includes("🎊"), "should contain confetti emoji");
    assert.ok(summary.includes("🥳"), "should contain party face emoji");
  });
});

describe("cross-reference: empty fields not emitted (from Elm output)", () => {
  it("empty description and location are absent", () => {
    const cal = parseCalendar(getFixture("empty-fields"));
    const ev = getEvent(cal);
    assert.equal(
      ev.getFirstPropertyValue("description"),
      null,
      "empty description should not be emitted"
    );
    assert.equal(
      ev.getFirstPropertyValue("location"),
      null,
      "empty location should not be emitted"
    );
  });

  it("summary is still present", () => {
    const cal = parseCalendar(getFixture("empty-fields"));
    const ev = getEvent(cal);
    assert.equal(
      ev.getFirstPropertyValue("summary"),
      "Event with empty fields"
    );
  });
});

describe("cross-reference: CalAddress not text-escaped (from Elm output)", () => {
  it("organizer email with semicolon is preserved", () => {
    const cal = parseCalendar(getFixture("special-email"));
    const ev = getEvent(cal);
    const org = ev.getFirstProperty("organizer");
    assert.ok(org, "organizer property should exist");
    assert.equal(
      org.getFirstValue(),
      "mailto:user;tag@example.com"
    );
  });
});

describe("cross-reference: trailing CRLF (from Elm output)", () => {
  it("all fixtures end with CRLF", () => {
    for (const fixture of fixtures) {
      assert.ok(
        fixture.ics.endsWith("\r\n"),
        `Fixture "${fixture.name}" should end with CRLF`
      );
    }
  });
});
